<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF4bjLgR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF4bjLgR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF4bjLgR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF4bjLgR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF4bjLgR\App_KernelDevDebugContainer([
    'container.build_hash' => 'F4bjLgR',
    'container.build_id' => '181b7f96',
    'container.build_time' => 1717792015,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF4bjLgR');
