<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xoTwox\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xoTwox/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xoTwox.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xoTwox\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xoTwox\App_KernelDevDebugContainer([
    'container.build_hash' => '0xoTwox',
    'container.build_id' => '26827283',
    'container.build_time' => 1716914609,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xoTwox');
