<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container99Rcyxl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container99Rcyxl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container99Rcyxl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container99Rcyxl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container99Rcyxl\App_KernelDevDebugContainer([
    'container.build_hash' => '99Rcyxl',
    'container.build_id' => 'd3cbcc10',
    'container.build_time' => 1718573809,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container99Rcyxl');
