<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'subject_add' => [[], ['_controller' => 'App\\Controller\\SubjectsController::add'], [], [['text', '/subjects/add']], [], [], []],
    'subject_show' => [[], ['_controller' => 'App\\Controller\\SubjectsController::show'], [], [['text', '/subjects/show']], [], [], []],
    'subject_list' => [[], ['_controller' => 'App\\Controller\\SubjectsController::list'], [], [['text', '/subjects/list']], [], [], []],
    'subject_edit' => [[], ['_controller' => 'App\\Controller\\SubjectsController::edit'], [], [['text', '/subjects/edit']], [], [], []],
    'subject_delete' => [[], ['_controller' => 'App\\Controller\\SubjectsController::delete'], [], [['text', '/subjects/delete']], [], [], []],
    'users_login' => [[], ['_controller' => 'App\\Controller\\UsersController::login'], [], [['text', '/users/login']], [], [], []],
    'users_addUser' => [[], ['_controller' => 'App\\Controller\\UsersController::addUser'], [], [['text', '/users/addUser']], [], [], []],
    'users_deleteUser' => [['id'], ['_controller' => 'App\\Controller\\UsersController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/deleteUser']], [], [], []],
    'users_getRole' => [['id'], ['_controller' => 'App\\Controller\\UsersController::getRole'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/getRole']], [], [], []],
    'users_setRole' => [['id'], ['_controller' => 'App\\Controller\\UsersController::changeRole'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/setRole']], [], [], []],
    'users_list' => [[], ['_controller' => 'App\\Controller\\UsersController::list'], [], [['text', '/users/list']], [], [], []],
    'App\Controller\SubjectsController::add' => [[], ['_controller' => 'App\\Controller\\SubjectsController::add'], [], [['text', '/subjects/add']], [], [], []],
    'App\Controller\SubjectsController::show' => [[], ['_controller' => 'App\\Controller\\SubjectsController::show'], [], [['text', '/subjects/show']], [], [], []],
    'App\Controller\SubjectsController::list' => [[], ['_controller' => 'App\\Controller\\SubjectsController::list'], [], [['text', '/subjects/list']], [], [], []],
    'App\Controller\SubjectsController::edit' => [[], ['_controller' => 'App\\Controller\\SubjectsController::edit'], [], [['text', '/subjects/edit']], [], [], []],
    'App\Controller\SubjectsController::delete' => [[], ['_controller' => 'App\\Controller\\SubjectsController::delete'], [], [['text', '/subjects/delete']], [], [], []],
    'App\Controller\UsersController::login' => [[], ['_controller' => 'App\\Controller\\UsersController::login'], [], [['text', '/users/login']], [], [], []],
    'App\Controller\UsersController::addUser' => [[], ['_controller' => 'App\\Controller\\UsersController::addUser'], [], [['text', '/users/addUser']], [], [], []],
    'App\Controller\UsersController::deleteUser' => [['id'], ['_controller' => 'App\\Controller\\UsersController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/deleteUser']], [], [], []],
    'App\Controller\UsersController::getRole' => [['id'], ['_controller' => 'App\\Controller\\UsersController::getRole'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/getRole']], [], [], []],
    'App\Controller\UsersController::changeRole' => [['id'], ['_controller' => 'App\\Controller\\UsersController::changeRole'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/setRole']], [], [], []],
    'App\Controller\UsersController::list' => [[], ['_controller' => 'App\\Controller\\UsersController::list'], [], [['text', '/users/list']], [], [], []],
];
